### ISSUE TITLE
don't panic when running on windows

### ISSUE THREAD

**Issue by zihan618** [cloudflare/tableflip#44]
My team use the project, but my part is not related to it.  
But once I run the program, the package panics and running failed.

**Comment by lmb** [comment]
Hi zihan,

Please provide me the output that you see. As is mentioned in the README, this project doesn't support Windows, so helping you here might be difficult.

**Comment by sagikazarmark** [comment]
A project of mine has just received a contribution, patching the upgrade functionality to make it work on Windows: sagikazarmark/modern-go-application#136

I believe the original issues that PR is trying to address are perfectly valid:

> The use-case for having it is specifically for those who develop and test locally on their own Windows desktop/laptop machines but run in production on Linux.

So, while I understand the _behavior_ implemented by this library cannot possibly work on Windows, I think it would be nice, if it wouldn't "fail" when someone develops a software on a Windows machine.

Unfortunately, I don't have a Windows machine, so I can't provide any details or solve the issue itself.

Would you be open to accepting a patch that makes the library "not fail" on Windows?

Personally, I believe it would be much better to solve this in the library itself, not in each application that is developed on Windows. If not, I will probably just accept the linked patch.

Thanks!

(/cc @kohenkatz, kinda hope that he can also provide a patch if you decide to accept it 🙂 )

**Comment by kohenkatz** [comment]
I'd be happy to provide a patch, but I'd appreciate some input on the preferred way to handle some of the API calls (in italics below).

Here are my initial thoughts:

- type `Fds`
   - function `Listen` - transparently pass to `net.Listen`
   - *functions `Conn`, `Listener` - these retrieve saved connections inherited from the parent. Since there is no such thing as inherited connections without the graceful restart process, should these just return `nil` always? In theory, it should never need to be called since we aren't doing restarts.*
   - *functions `AddConn`, `AddFile`, `AddListener` - these add connections to be tracked. As noted above, since there is no use for tracking these, should we just return `nil` with no other handling?*
- type `Upgrader`
   - function `New` - make a simplified version with only the `Fds` object but without any of the other properties.
   - function `HasParent` - always return `false`
   - function `Ready` - just return `nil` since there's nothing to do but we still need to let this be called.
   - function `Stop` - there's nothing to stop here, just do nothing.
   - function `WaitForParent` - just return `nil` since there's nothing to do.
   - *function `Upgrade` - throw an error "unsupported platform"*

There is also an organization question - since `fds.go` and `upgrader.go` have some code that would be used for both Windows and *nix, do they need to be split into separate files for type declaration and code so that the same type declarations can be used for both? The alternative is to recreate all type definitions in the `_windows.go` files, but that's probably a bad idea since it would allow them to diverge and cause problems. At the same time, right now there aren't that many files here, and we don't want to make it too confusing.

**Comment by lmb** [comment]
Thanks for providing more input :) I can see that this behaviour can be really annoying.

@kohenkatz the function mapping makes sense to me. However, Fds is embedded in Upgrader, so you can call Upgrader.Listen, Upgrader.AddConn, etc. I'd like to use this to provide a single "stub" struct that you can use to replace the Linux implementation if you so desire. This could be useful beyond Windows as well.

So my suggestion would be:
- Add a new ErrNotSupported, which is returned by `New` if the OS is not a Unix. We can use the same error for Upgrader.Upgrade I guess.
- Add a stub implementation as per your suggestions @kohenkatz, in a `testing` subpackage.

User code can then: 
- define an interface with the functions it requires
- If errors.Is(error from new, tableflip.ErrNotSupported) use `tableflip/testing.New` instead.

This way the changes to the Linux implementation are minimal, and adding "Windows support" is optional. We can document this in an example for the package.

Thoughts?

**Comment by kohenkatz** [comment]
That sounds like a good path forward. I am happy to submit a PR, but I probably won't get to it before Passover.

**Comment by lmb** [comment]
Closed in #48
